// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/49b1ac6a384fab428e0bad052b47f47ff8306193/once/index.d.ts
interface SimpleFunction<Result> {
  (...args: any[]): Result;
}

interface OnceFunction<Result> extends SimpleFunction<Result> {
  called: boolean;
  value: Result;
}

interface Once {
  <Result>(f: SimpleFunction<Result>): OnceFunction<Result>;
  proto: Function;
}

declare module "once" {
  var once: Once;
  export default once;
}
